export const BridgeMessageType = {
  VIEWER_READY: 'VIEWER_READY',
  ACTIVATE_TOOL: 'ACTIVATE_TOOL',
  DEACTIVATE_TOOL: 'DEACTIVATE_TOOL',
  FOCUS_MEASUREMENT: 'FOCUS_MEASUREMENT',
  DELETE_MEASUREMENT: 'DELETE_MEASUREMENT',
  MEASUREMENT_ADDED: 'MEASUREMENT_ADDED',
  MEASUREMENT_UPDATED: 'MEASUREMENT_UPDATED',
  MEASUREMENT_REMOVED: 'MEASUREMENT_REMOVED',
} as const;

export type MeasurementMessageType =
  | typeof BridgeMessageType.MEASUREMENT_ADDED
  | typeof BridgeMessageType.MEASUREMENT_UPDATED;
